version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-appv2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-10q1612tfue3f"
s3_prefix = "sam-app-appv2"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
