version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-appv2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1r2ycskj80q8i"
s3_prefix = "sam-app-appv2"
region = "ap-southeast-2"
profile = "yiai"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=dev BucketName=aiyi.demo.textract"

