AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 60

Parameters:
  Stage:
    Type: String
    Default: dev
  BucketName:
    Type: String
    Default: aiyi.demo.textexact

Resources:
  TextExtractSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub "textexact-sns-topic"
      TopicName: !Sub "textexact-sns-topic"
      Subscription:
        - Protocol: lambda
          Endpoint: !GetAtt TextExtractEndFunction.Arn

  TextExtractSNSTopicPolicy:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref TextExtractEndFunction
      Principal: sns.amazonaws.com
      Action: lambda:InvokeFunction
      SourceArn: !Ref TextExtractSNSTopic

  TextExtractEndFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handler.textExactEndHandler
      Runtime: nodejs12.x
      Policies:
        - AWSLambdaExecute

  TextExactStartFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          TEXT_EXTRACT_ROLE: !GetAtt TextExtractRole.Arn
          SNS_TOPIC: !Ref TextExtractSNSTopic
      Role: !GetAtt TextExtractRole.Arn
      CodeUri: src/
      Handler: handler.textexactStartHandler
      Runtime: nodejs12.x
      Events:
        PDFUploadEvent:
          Type: S3
          Properties:
            Bucket: !Ref S3Bucket
            Events: s3:ObjectCreated:*

  TextExtractRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "TextExtractRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "textract.amazonaws.com"
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWSLambdaExecute"
      Policies:
        - PolicyName: "TextExtractRoleAccess"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "sns:*"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "textract:*"
                Resource: "*"

  GetTextExtractResult:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt TextExtractRole.Arn
      CodeUri: src/
      Handler: handler.getTextExtractResult
      Runtime: nodejs12.x
      Events:
        TextExactStart:
          Type: HttpApi
          Properties:
            Path: /textexact
            Method: get

  MyHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref Stage
      Cors:
        AllowMethods: "'OPTIONS,POST,GET'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
